# Generated by Django 5.0.3 on 2024-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carmodel_fin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
